generator:
  class: mpRealtyAdminDoctrineGenerator
  param:
    model_class:           Evenement
    theme:                 mpReality
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          evenement
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        guid:         { label:  Identifiant }
        libelle:      { label:  Libellé }
        start_at:     { label:  Commence le}
        end_at:       { label:  Fini le}
        latitude:     { label:  Latitude }
        longitude:    { label:  Longitude }
        created_at:   { label:  Date de création, date_format: 'F' }
        updated_at:   { label:  Date de mise à jour, date_format: 'F' }
        is_tosync:    { label:  A synchroniser}
        exposition_list: { label:  Expositions}
      list:
        title: Liste des évènement
        display: [libelle, start_at, end_at, latitude, longitude, created_at, updated_at]
        sort:
          [start_at, desc]
        fields:
          created_at: { date_format: 'dd/MM/yyyy HH:mm' }
          updated_at: { date_format: 'dd/MM/yyyy HH:mm' }
          start_at:   { date_format: 'dd/MM/yyyy' }
          end_at:     { date_format: 'dd/MM/yyyy' }
        object_actions:
          _edit:      { label: Modifier, action: edit }
          _delete:    { label: Supprimer, action: delete }
        batch_actions:
          _delete:    {  label: Supprimer, action: delete , credentials: admin}
      filter:  ~
      form:
        display:
          [guid, libelle, start_at, end_at, latitude, longitude, exposition_list]
      edit:
        title: Modifier un évènement
      new:
        title: Créer un évènement
      show:    ~
      delete:  ~