generator:
  class: sfDoctrineRestGenerator
  param:
    model_class:   Evenement

    config:
      default:
#        fields:                                # list here the fields.
#          created_at:                  { date_format: 'Y-m-d\TH:i:s', tag_name: 'created' }      # for instance
#        formats_enabled:               [ json, xml, yaml ]    # enabled formats
#        formats_strict:                true
#        separator:                     ','     # separator used for multiple filters
      get:
#        additional_params:             []      # list here additionnal params names, which are not object properties
#        default_format:                json    # the default format of the response. If not set, will default to json. accepted values are "json", "xml" or "yaml"
#        display:                       []      # list here the fields to render in the response
#        embed_relations:               []      # list here relations to embed in the response
#        embedded_relations_hide:
#          Category:                    [id]    # you can hide fields inside a certain embedded relation
#        global_additional_fields:      []      # list here additionnal calculated global fields
        hide:                          [created_at, updated_at, is_tosync]    # list here the fields you don't want to expose
#        max_items:                     0       # uncomment to fix an absolute limit to the number of items in the response
#        object_additional_fields:      []      # list here additionnal calculated fields
#        pagination_enabled:            false   # set to true to activate the pagination
#        pagination_custom_page_size:   false   # set to true to allow the client to pass a page_size parameter
#        pagination_page_size:          100     # the default number of items in a page
#        sort_custom:                   false   # set to true to allow the client to pass a sort_by and a sort_order parameter
#        sort_default:                  []      # set to [column, asc|desc] in order to sort on a column
#        filters:                               # list here the filters
#          created_at:                  { date_format: 'd-m-Y', multiple: true }  # for instance
