<?php

/**
 * ContexteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContexteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContexteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contexte');
    }

  public function getForAutocomplete($name)
  {
    $results = $this->createQuery('contexte')
      ->select('contexte.libelle')
      ->where('contexte.libelle LIKE ?', '%'.$name.'%')
      ->orderBy('contexte.libelle')
      ->limit(20)
      ->execute();
    $results_array = array();

    foreach ($results as $result)
    {
      $results_array[$result->getLibelle()] = sprintf('%s', addslashes($result->getLibelle()));
    }

    return $results_array;
  }
}