<?php

/**
 * CspTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CspTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CspTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Csp');
    }
}