<?php

/**
 * DeleteLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeleteLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeleteLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeleteLog');
    }
}