<?php

/**
 * EvenementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EvenementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EvenementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Evenement');
    }
}