<?php

/**
 * EvenementExpositionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EvenementExpositionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EvenementExpositionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EvenementExposition');
    }
}