<?php

/**
 * ExpositionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExpositionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExpositionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Exposition');
    }

  public function getForAutocomplete($name)
  {
    $results = $this->createQuery('exposition')
      ->select('exposition.libelle')
      ->where('exposition.libelle LIKE ?', '%'.$name.'%')
      ->orderBy('exposition.libelle')
      ->limit(20)
      ->execute();
    $results_array = array();

    foreach ($results as $result)
    {
      $results_array[$result->getLibelle()] = sprintf('%s', addslashes($result->getLibelle()));
    }

    return $results_array;
  }
}