<?php

/**
 * ExpositionVisiteurNeedsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExpositionVisiteurNeedsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExpositionVisiteurNeedsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExpositionVisiteurNeeds');
    }

    /**
     * [doSelectJoinPerson description]
     * @param  [type] $query [description]
     * @return [type]        [description]
     */
    public static function doSelectJoinExposition($query)
    {
      $rootAlias = $query->getRootAlias();

      return $query->select($rootAlias . '.*, e.libelle')
        ->leftJoin($rootAlias . '.Exposition e');
    }
}