<?php

/**
 * ExpositionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExpositionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExpositionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Expositions');
    }
}