<?php

/**
 * ExpositionsParcoursTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExpositionsParcoursTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExpositionsParcoursTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExpositionsParcours');
    }
}