<?php

/**
 * FlotteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FlotteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FlotteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Flotte');
    }
}