<?php

/**
 * InteractifVariableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InteractifVariableTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InteractifVariableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('InteractifVariable');
    }
}