<?php

/**
 * InteractifTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InteractifTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InteractifTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Interactif');
    }

  public function getForAutocomplete($name)
  {
    $results = $this->createQuery('interactif')
      ->select('interactif.libelle')
      ->where('interactif.libelle LIKE ?', '%'.$name.'%')
      ->orderBy('interactif.libelle')
      ->limit(20)
      ->execute();
    $results_array = array();

    foreach ($results as $result)
    {
      $results_array[$result->getLibelle()] = sprintf('%s', addslashes($result->getLibelle()));
    }

    return $results_array;
  }

    public function symlinkDocument($interactif_id, $visiteur_id, $filename, $target){
        $interactifs_dir = sfConfig::get('sf_root_dir').'/web/interactif';
        $fileSystem = new sfFilesystem();
        if(!file_exists($interactifs_dir.'/'. $interactif_id . '/' . $visiteur_id . '/' . $filename)){
            if(!is_dir($interactifs_dir.'/'. $interactif_id )){
                $oldumask = umask(0);
                $fileSystem->mkdirs($interactifs_dir.'/'. $interactif_id, 0755);
                $fileSystem->chmod($interactifs_dir.'/'. $interactif_id, 0755);
                umask($oldumask);
            }
            if(!is_dir($interactifs_dir.'/'. $interactif_id . '/' . $visiteur_id)){
                $oldumask = umask(0);
                $fileSystem->mkdirs($interactifs_dir.'/'. $interactif_id . '/' . $visiteur_id, 0755);
                $fileSystem->chmod($interactifs_dir.'/'. $interactif_id . '/' . $visiteur_id, 0755);
                umask($oldumask);
            }

            symlink($target, $interactifs_dir.'/'. $interactif_id . '/' . $visiteur_id . '/' . $filename);
            return true;
            //exit;
        }
        return false;
    }
}