<?php

/**
 * LangueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LangueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LangueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Langue');
    }
}