<?php

/**
 * LangueExpositionVisiteurNeedsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LangueExpositionVisiteurNeedsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LangueExpositionVisiteurNeedsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LangueExpositionVisiteurNeeds');
    }
}