<?php

/**
 * MedailleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedailleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedailleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Medaille');
    }
}