<?php

/**
 * MedailleTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedailleTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedailleTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedailleType');
    }
}