<?php

/**
 * NotificationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotificationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotificationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Notification');
    }
}