<?php

/**
 * ParcoursTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ParcoursTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ParcoursTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Parcours');
    }
    
  public function getForAutocomplete($name)
  {
    $results = $this->createQuery('parcours')
      ->select('parcours.libelle')
      ->where('parcours.libelle LIKE ?', '%'.$name.'%')
      ->orderBy('parcours.libelle')
      ->limit(20)
      ->execute();
    $results_array = array();

    foreach ($results as $result)
    {
      $results_array[$result->getLibelle()] = sprintf('%s', addslashes($result->getLibelle()));
    }

    return $results_array;
  }
}