<?php

/**
 * PeripheriqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PeripheriqueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PeripheriqueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Peripherique');
    }
}