<?php

/**
 * PreferenceMediaVisiteurTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PreferenceMediaVisiteurTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PreferenceMediaVisiteurTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PreferenceMediaVisiteur');
    }
}