<?php

/**
 * PreferenceMediaExpositionVisiteurNeedsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PreferenceMediaExpositionVisiteurNeedsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PreferenceMediaExpositionVisiteurNeedsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PreferenceMediaExpositionVisiteurNeeds');
    }
}