<?php

/**
 * RulerzTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RulerzTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return RulerzTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Rulerz');
    }
}