<?php

/**
 * RulerzExecutionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RulerzExecutionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RulerzExecutionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RulerzExecution');
    }
}