<?php

/**
 * RulerzListenerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RulerzListenerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RulerzListenerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RulerzListener');
    }
}