<?php

/**
 * SentMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SentMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SentMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SentMessage');
    }
}