<?php

/**
 * TemplateMailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TemplateMailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TemplateMailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TemplateMail');
    }
}