<?php

/**
 * ThemeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ThemeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ThemeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Theme');
    }
}