<?php

/**
 * TypologieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypologieTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypologieTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Typologie');
    }
}