<?php

/**
 * UniversStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UniversStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UniversStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UniversStatus');
    }

}