<?php

/**
 * UniversTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UniversTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UniversTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Univers');
    }
}