<?php

/**
 * UserExpositionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserExpositionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserExpositionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserExposition');
    }
}