<?php

/**
 * VisiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VisiteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VisiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Visite');
    }
}