<?php

/**
 * VisiteurUniversStatusGainTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VisiteurUniversStatusGainTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VisiteurUniversStatusGainTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VisiteurUniversStatusGain');
    }

    public static function setNewVisiteurUniversStatus($new_univers_status, $univers_id, $visiteur_id, $gain_id = null, $gain_expiration_days = 0, $contexte_id = null){
        $new_visiteur_status = new VisiteurUniversStatusGain();
        $new_visiteur_status->setGuid(Guid::generate());
        $new_visiteur_status->setUniversStatusId($new_univers_status);
        $new_visiteur_status->setVisiteurId($visiteur_id);
        $new_visiteur_status->setGainId($gain_id);
        $new_visiteur_status->setUniversId($univers_id);
        $new_visiteur_status->setContexteId($contexte_id);
        if($gain_expiration_days === 0){
            $new_visiteur_status->setStatusGain(null);
            $new_visiteur_status->setExpirationGainDate(null);
        }else{
            $new_visiteur_status->setStatusGain('waiting');
            $date = date_create(date('Y-m-d'));
            date_add($date, date_interval_create_from_date_string($gain_expiration_days. ' days'));
            $new_visiteur_status->setExpirationGainDate(date_format($date, 'Y-m-d'));
        }

        $new_visiteur_status->save();
    }

    public static function hasNewStatus($visiteur_id, $medaille_id, $contexte_id = null){
       $visiteur_medailles = VisiteurTable::getMedaillesByUnivers($visiteur_id);

       foreach($visiteur_medailles as $univers_id =>  $visiteur_medaille){
           //print_r($visiteur_medaille);
          // exit;
            if(in_array($medaille_id, $visiteur_medaille['Medailles'])){
                $count_medaille = count($visiteur_medaille['Medailles']);

                foreach($visiteur_medaille['VisiteurStatus'] as $visiteur_status){

                    if(isset($visiteur_status['UniversStatus']) && count($visiteur_status['UniversStatus'])){
                        //$nb_min = $visiteur_status['UniversStatus']['nombre_min'];
                        $nb_max = $visiteur_status['UniversStatus']['nb_medaille'];
                        $current_level = $visiteur_status['UniversStatus']['level'];
                        $next_univers_status = Doctrine_Core::getTable("UniversStatus")
                            ->createQuery('us')
                            ->where('us.univers_id = ?', $univers_id)
                            ->andWhere('us.level = ?', $current_level+1)
                            ->limit(1)
                            ->fetchOne();

                        if($next_univers_status !== false && $count_medaille >= $next_univers_status->getNbMedaille()){
                            $gain_id = $next_univers_status->getGainId();
                            $expiration_days = 0;
                            if($gain_id){
                                $expiration_days = $next_univers_status->getGain()->getExpirationDays();
                            }
                            self::setNewVisiteurUniversStatus($next_univers_status->getGuid(), $univers_id, $visiteur_id, $gain_id, $expiration_days, $contexte_id);
                        }
                    }
                    break;
                }

            }
       }
    }
}