<?php

/**
 * VisiteurUniversStatusGain
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class VisiteurUniversStatusGain extends BaseVisiteurUniversStatusGain
{
    public function  __toString()
    {
        return $this->getGuid() ? $this->getGuid() : '';
    }

    public function __call($method, $arguments)
    {
        if($method == 'setGuid')
        {
            return $this->set('guid', Guid::generate());
        }
        else
        {
            return parent::__call($method, $arguments);
        }
    }

    public function  delete(Doctrine_Connection $conn = null)
    {
        $guid = $this->getGuid();

        parent::delete($conn);

        $delete_log = new DeleteLog();
        $delete_log->setGuid($guid);
        $delete_log->setModelName(get_class($this));
        $delete_log->save();
    }

    public function save(Doctrine_Connection $conn = null)
    {

        try{
            $this->setIsTosync(1);
            parent::save($conn);
            if($this->getGainId() != null){
                $send_email_visiteur_template_id = $this->getGain()->getSendEmailVisiteurTemplateId();
                $send_email_admin_template_id = $this->getGain()->getSendEmailAdminTemplateId();

                if($send_email_visiteur_template_id || $send_email_admin_template_id){

                    $visiteur = Doctrine_Core::getTable('Visiteur')->findOneBy('guid',  $this->getVisiteurId());
                    $gain = $this->getGain();
                    $univers_status = $this->getUniversStatus();

                    $visiteur_email = $visiteur->getEmail();
                    $admin_email = sfConfig::get('app_gain_admin_email', null);

                    $array_replace = array(
                        '$visiteur_pseudo' => $visiteur->getPseudoSon(),
                        '$visiteur_nom' => $visiteur->getNom(),
                        '$visiteur_prenom' => $visiteur->getPrenom(),
                        '$visiteur_adresse1' => $visiteur->getAdresse(),
                        '$visiteur_adresse2' => $visiteur->getAdresse2(),
                        '$visiteur_cp' => $visiteur->getCodePostal(),
                        '$visiteur_ville' => $visiteur->getVille(),
                        '$visiteur_num_mobile' => $visiteur->getNumMobile(),
                        '$visiteur_email' => $visiteur->getEmail(),
                        '$host_image_src' => sfConfig::get('app_host_image_src'),
                        '$gain_libelle' => $gain->getLibelle(),
                        '$gain_image' => $gain->getImage(),
                        '$gain_description' => $gain->getDescription(),
                        '$gain_start_at' => $gain->getStartAt(),
                        '$gain_end_at' => $gain->getEndAt(),
                        '$univers_status_level' => $univers_status->getLevel(),
                        '$univers_status_level_name' => $univers_status->getLevelName(),
                        '$univers_status_description' => $univers_status->getDescription(),
                        '$univers_status_libelle' => $univers_status->getLibelle()
                    );
                }
                // envoi d'un email au visiteur
                if($send_email_visiteur_template_id && $visiteur_email){
                    $template = Doctrine_Query::create()
                        ->from('TemplateMail t')
                        ->where('t.guid = ?', $send_email_visiteur_template_id)
                        ->fetchOne();
                    if($template !== false){
                        $template->sendEmail($visiteur_email, $array_replace);
                    }

                }
                // envoi d'un email a l'admin
                if($send_email_admin_template_id && $admin_email){
                    $template = Doctrine_Query::create()
                        ->from('TemplateMail t')
                        ->where('t.guid = ?', $send_email_admin_template_id)
                        ->fetchOne();
                    if($template !== false){
                        $template->sendEmail($admin_email, $array_replace);
                    }

                }

            }
        }catch(Exception $e){
		throw new Exception($e->getMessage());
        }

    }

}
