<?php

/**
 * XpTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class XpTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object XpTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Xp');
    }

    public function getTotalScore()
    {
		$res = Doctrine_Query::create()
          ->select("SUM(score) as total")
          ->from('Xp xp')->execute(array(), Doctrine::HYDRATE_ARRAY);

        return $res[0]['total'];
    }

    public function getTotalScoreByTypologieAndVisiteur($typologie_id, $visiteur_id)
    {
		$res = Doctrine_Query::create()
          ->select("SUM(score) as total")
          ->where("xp.typologie_id = ?")
          ->andWhere("xp.visiteur_id = ?")
          ->from('Xp xp')->execute(array($typologie_id, $visiteur_id), Doctrine::HYDRATE_ARRAY);

        return $res[0]['total'];
    }

}