generator:
  class: mpRealtyAdminDoctrineGenerator
  param:
    model_class:           TemplateMail
    theme:                 mpReality
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          template_mail
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        guid:         { label: Identifiant}
        key_search:   { label: Clé}
        suject:      { label: Sujet}
        content:      { label: Contenu}
        is_tosync:    { label: A synchroniser }
        created_at:   { label: Date de création, date_format: 'F' }
        updated_at:   { label: Date de mise à jour, date_format: 'F' }
      list:
        title: Liste des templates
        display: [ key_search, subject, created_at, updated_at]
        sort:
          [key_search, asc]
        fields:
          created_at: { date_format: 'dd/MM/yyyy HH:mm' }
          updated_at: { date_format: 'dd/MM/yyyy HH:mm' }
        object_actions:
          _edit:      { label: Modifier, action: edit }
          _delete:    { label: Supprimer, action: delete }
      filter:  ~
      form:
        display: [guid, key_search, subject, content]
      edit:
        title: Modifier un template mail
      new:
        title: Créer un template mail
      show:    ~
