generator:
  class: mpRealtyAdminDoctrineGenerator
  param:
    model_class:           Organisateur
    theme:                 mpReality
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          organisateur
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        guid:         { label:  Identifiant }
        created_at:   { label:  Date de création, date_format: 'F' }
        updated_at:   { label:  Date de mise à jour, date_format: 'F' }
        is_tosync:    {label: A synchroniser}
      list:
        title: Liste des organisateurs
        display: [libelle, created_at, updated_at]
        sort:
          [libelle, asc]
        fields:
          created_at: { date_format: 'dd/MM/yyyy HH:mm' }
          updated_at: { date_format: 'dd/MM/yyyy HH:mm' }
        object_actions:
          _edit:      { label: Modifier, action: edit }
          _delete:    { label: Supprimer, action: delete }
      filter:  ~
      form:
        display:
          [guid, libelle]
      edit:
        title: Modifier un organisateur
      new:
        title: Créer un organisateur
      show:    ~
      delete:    ~
      export:
        enabled: true
        title: organisateur export
        filename: exportation